version: '3.8'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: 682263059097.dkr.ecr.us-east-1.amazonaws.com/employee_api
    container_name: employeeAPI
    ports:
      - "8067:8067"
    environment:
      MAIL_SMTP_HOST: smtp.ethereal.email
      MAIL_SMTP_PORT: 587
      MAIL_SMTP_AUTH: true
      MAIL_SMTP_STARTTLS_ENABLE: true
      MAIL_USERNAME: ulises62@ethereal.email
      MAIL_PASSWORD: DAYvJsx7K9KmHB2cPq